### ISSUE TITLE
Cannot build 'SingleInstance' project from Chapter02

### ISSUE THREAD

**Issue by Swatto86** [zodiacon/Win10SysProgBookSamples#6]
Hi, great book btw, really enjoying it.  I have an issue with trying to build the projects in Chapter02 - it is saying I am missing nuget packages but they do exist (i have used the nuget package restore and checked that the files are on the filesystem in the place it is expected).

This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.

The missing file is ..\..\packages\wtl.10.0.9163\build\native\wtl.targets

**Comment by Swatto86** [comment]
I've solved this problem by copying the 'packages' folder to the root of the main directory (where all the chapters are listed).

**Comment by shalala66** [comment]
Also could be checked instead of copying packages:

1)
Right click on the project name to load it in Solution Explorer and select the Manage NuGet Packages, then select the Update tab to see packages that have an available updates from the selected Package source.

2)
Note that if after, there appears an error like "The missing file is "....\packages\wtl.10.0.9163\build\native\wtl.targets", remove these lines from .vcxproj file:

```xml
<Import Project="packages\wtl.10.0.9163\build\native\wtl.targets" Condition="Exists('packages\wtl.10.0.9163\build\native\wtl.targets')" />
```
```xml
<Error Condition="!Exists('packages\wtl.10.0.9163\build\native\wtl.targets')" Text="$([System.String]::Format('$(ErrorText)', 'packages\wtl.10.0.9163\build\native\wtl.targets'))" />
```

3)
On the Tools menu select the Options, then select General under the NuGet Package Manager for the Package Restore. Then select exactly the Packages.config for Default package management under Package Management and set both options under the Package Restore.

4)
If there generates MSB8020 error, then right click on the project name, select Properties and under the Solution configurations select General, then set Visual Studio 20xx (v14x) for Platform Toolset,- on my case I set Visual Studio 2019 (v142)
